# Elasticsearch configuration for Welcomer SNS Feed System
# Development environment optimized settings

# Cluster configuration
cluster.name: welcomer-cluster
node.name: welcomer-es-node

# Network configuration
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery configuration for single node
discovery.type: single-node

# Path configuration
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Memory configuration
bootstrap.memory_lock: true

# Security configuration
xpack.security.enabled: true
xpack.security.authc.api_key.enabled: true
xpack.security.transport.ssl.enabled: false
xpack.security.http.ssl.enabled: false

# Monitoring configuration
xpack.monitoring.collection.enabled: true

# Index configuration
action.auto_create_index: true
action.destructive_requires_name: true

# Performance settings for development
index.number_of_shards: 1
index.number_of_replicas: 0

# Search configuration
search.max_buckets: 65536

# Thread pool configuration
thread_pool.search.size: 4
thread_pool.search.queue_size: 1000

# Logging configuration
logger.root: INFO
logger.org.elasticsearch.transport: WARN
logger.org.elasticsearch.discovery: WARN

# Index lifecycle management
xpack.ilm.enabled: true

# Snapshot configuration for development
path.repo: ["/usr/share/elasticsearch/backup"]